### ISSUE TITLE
RuntimeError: [1] is setting up NCCL communicator and retreiving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: Broken pipe

### ISSUE THREAD

**Issue by WhXmURandom** [wenet-e2e/wespeaker#221]
<img width="719" alt="nccl" src="https://github.com/wenet-e2e/wespeaker/assets/109778621/1b7feb58-17d9-4285-93d4-5674c3c5df21">

**Comment by WhXmURandom** [comment]
重新安装与cuda11.1版本对应的torch后，又出现新的报错。
<img width="720" alt="api" src="https://github.com/wenet-e2e/wespeaker/assets/109778621/91801412-db27-4453-a745-6d8f9105e844">

**Comment by cdliang11** [comment]
> 重新安装与cuda11.1版本对应的torch后，又出现新的报错。 <img alt="api" width="720" src="https://user-images.githubusercontent.com/109778621/281450166-91801412-db27-4453-a745-6d8f9105e844.png">


把实验路径删了，或者注释掉以下代码试试：
https://github.com/wenet-e2e/wespeaker/blob/6550a2ae9b431662b78df393af4440be23a787df/wespeaker/bin/train.py#L60-L61

**Comment by WhXmURandom** [comment]
把modeldir删掉了，现在卡在这里十多分钟，是正常的吗？
<img width="728" alt="11" src="https://github.com/wenet-e2e/wespeaker/assets/109778621/09fe68ff-6a11-408b-8165-2775244ef3d4">

**Comment by cdliang11** [comment]
看起来是nccl的问题

**Comment by cdliang11** [comment]
https://github.com/wenet-e2e/wespeaker/blob/6550a2ae9b431662b78df393af4440be23a787df/wespeaker/bin/train.py#L52
换成gloo试试

**Comment by WhXmURandom** [comment]
换成gloo似乎也不行
<img width="687" alt="微信图片_20231109101517" src="https://github.com/wenet-e2e/wespeaker/assets/109778621/341e8008-5006-43f5-9123-7ed7efdc8a7c">

**Comment by WhXmURandom** [comment]
应该是卡在了dist.barrier(device_ids=[gpu])

**Comment by WhXmURandom** [comment]
在脚本前加入NCCL_P2P_DISABLE=1可以多卡跑了

**Comment by WhXmURandom** [comment]
NCCL_P2P_DISABLE=1  torchrun --standalone --nnodes=1 --nproc_per_node=$num_gpus \

> > 在脚本前加入NCCL_P2P_DISABLE=1可以多卡跑了
> 
> 请问是在哪个脚本加入这个呢 我在wespeaker/examples/cnceleb/v2的run.sh里尝试加入这句话然后./run.sh运行还是不行 <img alt="企业微信截图_17066959961284" width="633" src="https://private-user-images.githubusercontent.com/46421217/301122509-daa21802-b37a-43ca-988b-039955e96091.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTYzMTgsIm5iZiI6MTcwNjY5NjAxOCwicGF0aCI6Ii80NjQyMTIxNy8zMDExMjI1MDktZGFhMjE4MDItYjM3YS00M2NhLTk4OGItMDM5OTU1ZTk2MDkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDEwMTMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxMTlmNGY0OWUyNDJjYzgzYmRhNzhiNzEwMDQ5NDI5MzgyMDA2ZWU3OTM3NWRmZjNjYWM2MGQ0OWU5ODQwMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VRB77LmxSCLXJRR800LS3dFDC7GzFukoYyjA0oUZo1g">

**Comment by wcqy-ye** [comment]
> NCCL_P2P_DISABLE=1 torchrun --standalone --nnodes=1 --nproc_per_node=$num_gpus \
> 
> > > 在脚本前加入NCCL_P2P_DISABLE=1可以多卡跑了
> > 
> > 
> > 请问是在哪个脚本加入这个呢 我在wespeaker/examples/cnceleb/v2的run.sh里尝试加入这句话然后./run.sh运行还是不行 <img alt="企业微信截图_17066959961284" width="633" src="https://private-user-images.githubusercontent.com/46421217/301122509-daa21802-b37a-43ca-988b-039955e96091.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTYzMTgsIm5iZiI6MTcwNjY5NjAxOCwicGF0aCI6Ii80NjQyMTIxNy8zMDExMjI1MDktZGFhMjE4MDItYjM3YS00M2NhLTk4OGItMDM5OTU1ZTk2MDkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDEwMTMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxMTlmNGY0OWUyNDJjYzgzYmRhNzhiNzEwMDQ5NDI5MzgyMDA2ZWU3OTM3NWRmZjNjYWM2MGQ0OWU5ODQwMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VRB77LmxSCLXJRR800LS3dFDC7GzFukoYyjA0oUZo1g">

好像还是不行 并且我尝试zhi只使用一个gpu，还是会报错
![image](https://github.com/wenet-e2e/wespeaker/assets/46421217/c8931fc8-1228-46c1-8f7f-bc74dc8806b7)
并且很奇怪的是像是刚刚运行就错误了 请问您有什么想法或者知道怎么做吗
<img width="809" alt="企业微信截图_1706779076569" src="https://github.com/wenet-e2e/wespeaker/assets/46421217/adf18156-13f4-41be-b334-87bb0301758f">

**Comment by WhXmURandom** [comment]
> > NCCL_P2P_DISABLE=1 torchrun --standalone --nnodes=1 --nproc_per_node=$num_gpus \
> > > > 在脚本前加入NCCL_P2P_DISABLE=1可以多卡跑了
> > > 
> > > 
> > > 请问是在哪个脚本加入这个呢 我在wespeaker/examples/cnceleb/v2的run.sh里尝试加入这句话然后./run.sh运行还是不行 <img alt="企业微信截图_17066959961284" width="633" src="https://private-user-images.githubusercontent.com/46421217/301122509-daa21802-b37a-43ca-988b-039955e96091.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTYzMTgsIm5iZiI6MTcwNjY5NjAxOCwicGF0aCI6Ii80NjQyMTIxNy8zMDExMjI1MDktZGFhMjE4MDItYjM3YS00M2NhLTk4OGItMDM5OTU1ZTk2MDkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDEwMTMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxMTlmNGY0OWUyNDJjYzgzYmRhNzhiNzEwMDQ5NDI5MzgyMDA2ZWU3OTM3NWRmZjNjYWM2MGQ0OWU5ODQwMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VRB77LmxSCLXJRR800LS3dFDC7GzFukoYyjA0oUZo1g">
> 
> 好像还是不行 并且我尝试zhi只使用一个gpu，还是会报错 ![image](https://private-user-images.githubusercontent.com/46421217/301449650-c8931fc8-1228-46c1-8f7f-bc74dc8806b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3ODE3NzIsIm5iZiI6MTcwNjc4MTQ3MiwicGF0aCI6Ii80NjQyMTIxNy8zMDE0NDk2NTAtYzg5MzFmYzgtMTIyOC00NmMxLThmN2YtYmM3NGRjODgwNmI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA5NTc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlYTY0MDc1ZGJjNTI2NWQ5YmZkMmQ3MGQyYTBhNWYyYTQxNjA3YjcxMWFhOWJlYzlhOGI4ZTE2ZWZmY2ZmZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yimKp-hTi1-Ie8aal1L_qXeIVxwhQX4GqjIEsC1M8y4) 并且很奇怪的是像是刚刚运行就错误了 请问您有什么想法或者知道怎么做吗 <img alt="企业微信截图_1706779076569" width="809" src="https://private-user-images.githubusercontent.com/46421217/301449945-adf18156-13f4-41be-b334-87bb0301758f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3ODE3NzIsIm5iZiI6MTcwNjc4MTQ3MiwicGF0aCI6Ii80NjQyMTIxNy8zMDE0NDk5NDUtYWRmMTgxNTYtMTNmNC00MWJlLWIzMzQtODdiYjAzMDE3NThmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA5NTc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyOGJjZWFjMGVkMjM4MDEwNmVmOWRmODkyZTRiZDM5YzU5ZDIxZmEzZjZmMjdkNjUyOGI2YTQ1ZTc3YThiYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.igYYxnSEzsevUaNUwnN9XOqptonCxEv413TCW3oyJB0">

你把exp_dir删除再运行

**Comment by wcqy-ye** [comment]
> > > NCCL_P2P_DISABLE=1 torchrun --standalone --nnodes=1 --nproc_per_node=$num_gpus \
> > > > > 在脚本前加入NCCL_P2P_DISABLE=1可以多卡跑了
> > > > 
> > > > 
> > > > 请问是在哪个脚本加入这个呢 我在wespeaker/examples/cnceleb/v2的run.sh里尝试加入这句话然后./run.sh运行还是不行 <img alt="企业微信截图_17066959961284" width="633" src="https://private-user-images.githubusercontent.com/46421217/301122509-daa21802-b37a-43ca-988b-039955e96091.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTYzMTgsIm5iZiI6MTcwNjY5NjAxOCwicGF0aCI6Ii80NjQyMTIxNy8zMDExMjI1MDktZGFhMjE4MDItYjM3YS00M2NhLTk4OGItMDM5OTU1ZTk2MDkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDEwMTMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxMTlmNGY0OWUyNDJjYzgzYmRhNzhiNzEwMDQ5NDI5MzgyMDA2ZWU3OTM3NWRmZjNjYWM2MGQ0OWU5ODQwMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VRB77LmxSCLXJRR800LS3dFDC7GzFukoYyjA0oUZo1g">
> > 
> > 
> > 好像还是不行 并且我尝试zhi只使用一个gpu，还是会报错 ![image](https://private-user-images.githubusercontent.com/46421217/301449650-c8931fc8-1228-46c1-8f7f-bc74dc8806b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3ODE3NzIsIm5iZiI6MTcwNjc4MTQ3MiwicGF0aCI6Ii80NjQyMTIxNy8zMDE0NDk2NTAtYzg5MzFmYzgtMTIyOC00NmMxLThmN2YtYmM3NGRjODgwNmI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA5NTc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlYTY0MDc1ZGJjNTI2NWQ5YmZkMmQ3MGQyYTBhNWYyYTQxNjA3YjcxMWFhOWJlYzlhOGI4ZTE2ZWZmY2ZmZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yimKp-hTi1-Ie8aal1L_qXeIVxwhQX4GqjIEsC1M8y4) 并且很奇怪的是像是刚刚运行就错误了 请问您有什么想法或者知道怎么做吗 <img alt="企业微信截图_1706779076569" width="809" src="https://private-user-images.githubusercontent.com/46421217/301449945-adf18156-13f4-41be-b334-87bb0301758f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3ODE3NzIsIm5iZiI6MTcwNjc4MTQ3MiwicGF0aCI6Ii80NjQyMTIxNy8zMDE0NDk5NDUtYWRmMTgxNTYtMTNmNC00MWJlLWIzMzQtODdiYjAzMDE3NThmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA5NTc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyOGJjZWFjMGVkMjM4MDEwNmVmOWRmODkyZTRiZDM5YzU5ZDIxZmEzZjZmMjdkNjUyOGI2YTQ1ZTc3YThiYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.igYYxnSEzsevUaNUwnN9XOqptonCxEv413TCW3oyJB0">
> 
> 你把exp_dir删除再运行

好的 万分感谢 解决了
